config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount ActionCable.server => "/cable"

  root to: "chat_rooms#index"

  resources :chat_rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  validates :body, presence: true, length: {minimum: 1}

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end

  after_create_commit{ MessageBroadcastJob.perform_later self }
end

app/models/user.rb
class User < ApplicationRecord

  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  validates :email, uniqueness: true

  def name
    # whoaaaaaa you can do stuff like this in rails?!
    # AWESOME!!!!
    email.split("@")[0]
  end

  def is_online
    self.update_attributes(online: true)
  end

  def is_offline
    self.update_attributes(online: false)
  end

  after_update_commit {AppearanceBroadcastJob.perform_later self}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def require_user
    redirect_to "/users/sign_in" unless current_user
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :require_user

  def index
    @chat_rooms = ChatRoom.all
    @users = User.all
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      puts "OK"
      redirect_to chat_rooms_path
    else
      raise "Messed up!"
    end
  end

  def destroy
    @chat_room = ChatRoom.find(params[:id])
    if @chat_room.destroy
      puts "OK"
      redirect_to chat_rooms_path
    else
      raise "Messed up!"
    end
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}", opts
  end
end

app/views/chat_rooms/index.html.erb
<h1>Chat rooms</h1>

<p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>

<h3>Online Users:</h3>
<ul>
  <div id="online-users">
    <% @users.each do |user| %>
      <% if user.online %>
        <li><%= user.name %></li>
      <% end %>
    <% end %>
  </div>
</ul>

<ul>
  <% @chat_rooms.each do |room| %>
    <li><%= link_to "Enter #{room.title}", chat_room_path(room) %></li>
  <% end %>
</ul>

app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/show.html.erb
<h1><%= @chat_room.title %></h1>


<div id="messages" data-chat-room-id="<%= @chat_room.id %>">
  <%= render @chat_room.messages %>
</div>
<div class="form-group">
  <textarea id="message-content" cols="80" rows="1"></textarea>
  <small class="text-muted">At least 1 character, please!</small>
</div>

<% if current_user.id == @chat_room.user_id %>
  <p class="lead"><%= link_to 'Delete this Room?', @chat_room, method: :delete, data: {confirm: "Are you sure? All messages will be deleted"}, class: 'btn btn-primary' %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActionCableTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to('Logout', destroy_user_session_path, class: 'btn btn-primary', :method => :delete) %>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-1">
        <%= gravatar_for message.user %>
      </div>
      <div class="col-md-11">
        <p class="card-text">
          <span class="text-muted"><%= message.user.name %> at <%= message.timestamp %> says</span><br>
          <%= message.body %>
        </p>
      </div>
    </div>
  </div>
</div>